{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meridian.serviceAccountName" . }}
  namespace: {{ include "meridian.namespace" . }}
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
