import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";
import { api } from "../api/client";
import { HarnessSetupEditor } from "../components/HarnessSetupEditor";
const setup = {id:"setup",harness:"opencode",name:"Personal",revision:"r1",default:true,deleted:false,resourceVersion:3,createdAt:"2026-09-07T00:00:00Z"};
afterEach(() => {cleanup();vi.restoreAllMocks();});
it("edits the loaded version, reviews sanitized content, and saves with stable retries", async () => {
 const bundle = {harness:"opencode" as const, files:[{path:".config/opencode/AGENTS.md",content:"original"}], dependencies:[]};
 const contents = {...setup,expectedResourceVersion:2,bundle};
 vi.spyOn(api,"harnessSetupContents").mockResolvedValue(contents);
 const preview = vi.spyOn(api,"previewHarnessSetup").mockResolvedValue({bundle:{...bundle,files:[{path:bundle.files[0]!.path,content:"reviewed"}]},issues:[{path:"sensitive",reason:"excluded"}],digest:"digest"});
 const save = vi.spyOn(api,"importHarnessSetup").mockRejectedValueOnce(new TypeError("fetch failed")).mockResolvedValue(setup);
 const close = vi.fn();const cache = new QueryClient();
 render(<QueryClientProvider client={cache}><HarnessSetupEditor setup={setup} onClose={close}/></QueryClientProvider>);
 await userEvent.click(await screen.findByText(".config/opencode/AGENTS.md"));
 const editor = screen.getByLabelText("Contents of .config/opencode/AGENTS.md");
 await userEvent.clear(editor);await userEvent.type(editor,"edited");
 await userEvent.type(screen.getByLabelText("Skill name"),"review-code");await userEvent.click(screen.getByRole("button",{name:"Add skill"}));
 await userEvent.click(screen.getByRole("button",{name:"Review changes"}));
 expect(preview.mock.calls[0]?.[0].files).toHaveLength(2);
 expect(preview.mock.calls[0]?.[0].files[0]?.content).toBe("edited");
 expect(await screen.findByRole("button",{name:"Save changes"})).toBeDisabled();
 await userEvent.click(screen.getByLabelText("I reviewed the exclusions"));
 await userEvent.click(screen.getByRole("button",{name:"Save changes"}));
 await screen.findByRole("alert");await userEvent.click(screen.getByRole("button",{name:"Save changes"}));
 await waitFor(() => expect(close).toHaveBeenCalled());
 expect(save.mock.calls[0]?.[0].expectedResourceVersion).toBe(2);
 expect(save.mock.calls[0]?.[0].bundle.files[0]?.content).toBe("reviewed");
 expect(save.mock.calls[0]?.[1]).toBe(save.mock.calls[1]?.[1]);
 expect(cache.getQueryCache().getAll()).toHaveLength(0);
});
