// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	ArchiveThreadOperation:              []string{},
	CancelRunOperation:                  []string{},
	CancelThreadOperation:               []string{},
	CaptureMomentOperation:              []string{},
	CreateBrowserSessionOperation:       []string{},
	CreateCapsuleOperation:              []string{},
	CreateCapsuleDeliveryOperation:      []string{},
	CreateCapsulePreviewTicketOperation: []string{},
	CreateProjectOperation:              []string{},
	CreateProjectThreadOperation:        []string{},
	CreateRunAttachTicketOperation:      []string{},
	CreateShardOperation:                []string{},
	CreateThreadOperation:               []string{},
	DeleteCapsuleOperation:              []string{},
	DeleteSecretOperation:               []string{},
	DeleteThreadOperation:               []string{},
	ExportCapsuleWorkspaceOperation:     []string{},
	GetCapabilitiesOperation:            []string{},
	GetCapsuleOperation:                 []string{},
	GetCapsuleGitDiffOperation:          []string{},
	GetCapsuleGitStatusOperation:        []string{},
	GetDeliveryOperation:                []string{},
	GetMomentOperation:                  []string{},
	GetProjectOperation:                 []string{},
	GetProjectThreadIntentOperation:     []string{},
	GetRunOperation:                     []string{},
	GetThreadOperation:                  []string{},
	GetTimelineOperation:                []string{},
	InspectCapsuleDeliveryOperation:     []string{},
	ListCapsuleDeliveriesOperation:      []string{},
	ListCapsuleFilesOperation:           []string{},
	ListCapsulePreviewPortsOperation:    []string{},
	ListCapsulesOperation:               []string{},
	ListHarnessProfilesOperation:        []string{},
	ListMomentsOperation:                []string{},
	ListProjectsOperation:               []string{},
	ListRunEventsOperation:              []string{},
	ListRunsOperation:                   []string{},
	ListSecretsOperation:                []string{},
	ListThreadBlocksOperation:           []string{},
	ListThreadsOperation:                []string{},
	PauseCapsuleOperation:               []string{},
	PutSecretOperation:                  []string{},
	ReadCapsuleFileOperation:            []string{},
	RespondThreadOperation:              []string{},
	ResumeCapsuleOperation:              []string{},
	ResumeThreadOperation:               []string{},
	RewindCapsuleOperation:              []string{},
	SealCapsuleOperation:                []string{},
	SendThreadMessageOperation:          []string{},
	StartRunOperation:                   []string{},
	StartThreadOperation:                []string{},
	StreamRunEventsOperation:            []string{},
	StreamThreadBlocksOperation:         []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
