// Code generated by ogen, DO NOT EDIT.

package client

// ArchiveThreadParams is parameters of archiveThread operation.
type ArchiveThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// AttachRunWebSocketParams is parameters of attachRunWebSocket operation.
type AttachRunWebSocketParams struct {
	RunId  string
	Ticket string
}

// CancelRunParams is parameters of cancelRun operation.
type CancelRunParams struct {
	RunId          string
	IdempotencyKey string
}

// CancelThreadParams is parameters of cancelThread operation.
type CancelThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// CaptureMomentParams is parameters of captureMoment operation.
type CaptureMomentParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// CreateCapsuleParams is parameters of createCapsule operation.
type CreateCapsuleParams struct {
	ProjectId      string
	IdempotencyKey string
}

// CreateCapsuleDeliveryParams is parameters of createCapsuleDelivery operation.
type CreateCapsuleDeliveryParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// CreateCapsulePreviewTicketParams is parameters of createCapsulePreviewTicket operation.
type CreateCapsulePreviewTicketParams struct {
	CapsuleId string
	Port      int
}

// CreateProjectParams is parameters of createProject operation.
type CreateProjectParams struct {
	IdempotencyKey string
}

// CreateProjectThreadParams is parameters of createProjectThread operation.
type CreateProjectThreadParams struct {
	ProjectId      string
	IdempotencyKey string
}

// CreateRunAttachTicketParams is parameters of createRunAttachTicket operation.
type CreateRunAttachTicketParams struct {
	RunId string
	After OptInt64 `json:",omitempty,omitzero"`
}

// CreateShardParams is parameters of createShard operation.
type CreateShardParams struct {
	MomentId       string
	IdempotencyKey string
}

// CreateThreadParams is parameters of createThread operation.
type CreateThreadParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// DeleteCapsuleParams is parameters of deleteCapsule operation.
type DeleteCapsuleParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// DeleteSecretParams is parameters of deleteSecret operation.
type DeleteSecretParams struct {
	IdempotencyKey string
	SecretName     string
}

// DeleteThreadParams is parameters of deleteThread operation.
type DeleteThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// ExportCapsuleWorkspaceParams is parameters of exportCapsuleWorkspace operation.
type ExportCapsuleWorkspaceParams struct {
	CapsuleId string
}

// GetCapsuleParams is parameters of getCapsule operation.
type GetCapsuleParams struct {
	CapsuleId string
}

// GetCapsuleGitDiffParams is parameters of getCapsuleGitDiff operation.
type GetCapsuleGitDiffParams struct {
	CapsuleId string
}

// GetCapsuleGitStatusParams is parameters of getCapsuleGitStatus operation.
type GetCapsuleGitStatusParams struct {
	CapsuleId string
}

// GetDeliveryParams is parameters of getDelivery operation.
type GetDeliveryParams struct {
	DeliveryId string
}

// GetMomentParams is parameters of getMoment operation.
type GetMomentParams struct {
	MomentId string
}

// GetProjectParams is parameters of getProject operation.
type GetProjectParams struct {
	ProjectId string
}

// GetProjectThreadIntentParams is parameters of getProjectThreadIntent operation.
type GetProjectThreadIntentParams struct {
	IntentId string
}

// GetRunParams is parameters of getRun operation.
type GetRunParams struct {
	RunId string
}

// GetThreadParams is parameters of getThread operation.
type GetThreadParams struct {
	ThreadId string
}

// GetTimelineParams is parameters of getTimeline operation.
type GetTimelineParams struct {
	TimelineId string
}

// InspectCapsuleDeliveryParams is parameters of inspectCapsuleDelivery operation.
type InspectCapsuleDeliveryParams struct {
	CapsuleId string
}

// ListCapsuleDeliveriesParams is parameters of listCapsuleDeliveries operation.
type ListCapsuleDeliveriesParams struct {
	CapsuleId string
	Cursor    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// ListCapsuleFilesParams is parameters of listCapsuleFiles operation.
type ListCapsuleFilesParams struct {
	CapsuleId string
	Path      OptString `json:",omitempty,omitzero"`
	After     OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// ListCapsulePreviewPortsParams is parameters of listCapsulePreviewPorts operation.
type ListCapsulePreviewPortsParams struct {
	CapsuleId string
}

// ListCapsulesParams is parameters of listCapsules operation.
type ListCapsulesParams struct {
	ProjectId string
	Cursor    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// ListHarnessProfilesParams is parameters of listHarnessProfiles operation.
type ListHarnessProfilesParams struct {
	CapsuleId string
}

// ListMomentsParams is parameters of listMoments operation.
type ListMomentsParams struct {
	CapsuleId string
	Cursor    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// ListProjectsParams is parameters of listProjects operation.
type ListProjectsParams struct {
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
}

// ListRunEventsParams is parameters of listRunEvents operation.
type ListRunEventsParams struct {
	RunId string
	After OptInt64 `json:",omitempty,omitzero"`
	Limit OptInt   `json:",omitempty,omitzero"`
}

// ListRunsParams is parameters of listRuns operation.
type ListRunsParams struct {
	CapsuleId string
	Cursor    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// ListSecretsParams is parameters of listSecrets operation.
type ListSecretsParams struct {
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
}

// ListThreadBlocksParams is parameters of listThreadBlocks operation.
type ListThreadBlocksParams struct {
	ThreadId string
	After    OptInt64 `json:",omitempty,omitzero"`
	Limit    OptInt   `json:",omitempty,omitzero"`
}

// ListThreadsParams is parameters of listThreads operation.
type ListThreadsParams struct {
	CapsuleId string
	Cursor    OptString `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

// PauseCapsuleParams is parameters of pauseCapsule operation.
type PauseCapsuleParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// PutSecretParams is parameters of putSecret operation.
type PutSecretParams struct {
	IdempotencyKey string
	SecretName     string
}

// ReadCapsuleFileParams is parameters of readCapsuleFile operation.
type ReadCapsuleFileParams struct {
	CapsuleId string
	Path      string
}

// RespondThreadParams is parameters of respondThread operation.
type RespondThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// ResumeCapsuleParams is parameters of resumeCapsule operation.
type ResumeCapsuleParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// ResumeThreadParams is parameters of resumeThread operation.
type ResumeThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// RewindCapsuleParams is parameters of rewindCapsule operation.
type RewindCapsuleParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// SealCapsuleParams is parameters of sealCapsule operation.
type SealCapsuleParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// SendThreadMessageParams is parameters of sendThreadMessage operation.
type SendThreadMessageParams struct {
	ThreadId       string
	IdempotencyKey string
}

// StartRunParams is parameters of startRun operation.
type StartRunParams struct {
	CapsuleId      string
	IdempotencyKey string
}

// StartThreadParams is parameters of startThread operation.
type StartThreadParams struct {
	ThreadId       string
	IdempotencyKey string
}

// StreamRunEventsParams is parameters of streamRunEvents operation.
type StreamRunEventsParams struct {
	RunId       string
	After       OptInt64  `json:",omitempty,omitzero"`
	LastEventID OptString `json:",omitempty,omitzero"`
}

// StreamThreadBlocksParams is parameters of streamThreadBlocks operation.
type StreamThreadBlocksParams struct {
	ThreadId    string
	After       OptInt64  `json:",omitempty,omitzero"`
	LastEventID OptString `json:",omitempty,omitzero"`
}
