// Code generated by ogen, DO NOT EDIT.
package client

type ArchiveThreadRes interface {
	archiveThreadRes()
}

type AttachRunWebSocketRes interface {
	attachRunWebSocketRes()
}

type CancelRunRes interface {
	cancelRunRes()
}

type CancelThreadRes interface {
	cancelThreadRes()
}

type CaptureMomentRes interface {
	captureMomentRes()
}

type CreateCapsulePreviewTicketRes interface {
	createCapsulePreviewTicketRes()
}

type CreateCapsuleRes interface {
	createCapsuleRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateRunAttachTicketRes interface {
	createRunAttachTicketRes()
}

type CreateShardRes interface {
	createShardRes()
}

type CreateThreadRes interface {
	createThreadRes()
}

type DeleteCapsuleRes interface {
	deleteCapsuleRes()
}

type DeleteThreadRes interface {
	deleteThreadRes()
}

type GetCapabilitiesRes interface {
	getCapabilitiesRes()
}

type GetCapsuleGitDiffRes interface {
	getCapsuleGitDiffRes()
}

type GetCapsuleGitStatusRes interface {
	getCapsuleGitStatusRes()
}

type GetCapsuleRes interface {
	getCapsuleRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetMomentRes interface {
	getMomentRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetReadinessRes interface {
	getReadinessRes()
}

type GetRunRes interface {
	getRunRes()
}

type GetThreadRes interface {
	getThreadRes()
}

type GetTimelineRes interface {
	getTimelineRes()
}

type ListCapsulePreviewPortsRes interface {
	listCapsulePreviewPortsRes()
}

type ListCapsulesRes interface {
	listCapsulesRes()
}

type ListHarnessProfilesRes interface {
	listHarnessProfilesRes()
}

type ListMomentsRes interface {
	listMomentsRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListRunEventsRes interface {
	listRunEventsRes()
}

type ListRunsRes interface {
	listRunsRes()
}

type ListThreadBlocksRes interface {
	listThreadBlocksRes()
}

type ListThreadsRes interface {
	listThreadsRes()
}

type PauseCapsuleRes interface {
	pauseCapsuleRes()
}

type RespondThreadRes interface {
	respondThreadRes()
}

type ResumeCapsuleRes interface {
	resumeCapsuleRes()
}

type ResumeThreadRes interface {
	resumeThreadRes()
}

type RewindCapsuleRes interface {
	rewindCapsuleRes()
}

type SealCapsuleRes interface {
	sealCapsuleRes()
}

type SendThreadMessageRes interface {
	sendThreadMessageRes()
}

type StartRunRes interface {
	startRunRes()
}

type StartThreadRes interface {
	startThreadRes()
}

type StreamRunEventsRes interface {
	streamRunEventsRes()
}

type StreamThreadBlocksRes interface {
	streamThreadBlocksRes()
}
